name: Theme Backup (ZIP to Releases)

on:
  workflow_dispatch: {}          # kézi indítás (Actions > Run workflow)
  push:
    branches: [ main ]           # push-ra is
  schedule:
    - cron: '0 * * * *'          # minden egész órában (UTC)

permissions:
  contents: write

concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: false

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Itt már nincs időkorlátozás, mindig fut
      - name: Prepare ZIP with BUILDINFO
        run: |
          mkdir -p dist
          TS_UTC="$(date -u +'%Y%m%d-%H%M%S')"
          TS_BUD="$(TZ=Europe/Budapest date +'%Y%m%d-%H%M%S')"
          ZIPNAME="partdo-child-${TS_BUD}.zip"

          COMMIT_SHA="${GITHUB_SHA}"
          COMMIT_MSG="$(git log -1 --pretty=%B | tr -d '\r')"
          REPO="${GITHUB_REPOSITORY}"
          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          BRANCH="${GITHUB_REF_NAME}"

          cat > BUILDINFO.txt <<EOF
REPO=${REPO}
BRANCH=${BRANCH}
COMMIT_SHA=${COMMIT_SHA}
COMMIT_MSG=${COMMIT_MSG}
UTC_TIME=${TS_UTC}
BUD_TIME=${TS_BUD}
RUN_URL=${RUN_URL}
EOF

          zip -j "dist/${ZIPNAME}" functions.php style.css .gitignore BUILDINFO.txt

          echo "ZIP_NAME=${ZIPNAME}" >> $GITHUB_ENV
          echo "TAG_NAME=backup-${TS_BUD}-${GITHUB_RUN_ID}" >> $GITHUB_ENV
          echo "RELEASE_NAME=Auto backup ${TS_BUD} (RUN ${GITHUB_RUN_ID})" >> $GITHUB_ENV
          echo "RELEASE_BODY=Automated backup for ${BRANCH}%0ARepo: ${REPO}%0ACommit: ${COMMIT_SHA}%0ARun: ${RUN_URL}" >> $GITHUB_ENV

      - name: Create Release & Upload ZIP
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: ${{ env.RELEASE_BODY }}
          files: dist/${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
