name: Theme Backup (ZIP to Releases)

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *'   # minden nap 02:00 UTC

permissions:
  contents: write

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare ZIP with BUILDINFO
        run: |
          mkdir -p dist
          ts="$(date -u +'%Y%m%d-%H%M%S')"
          zipname="partdo-child-${ts}.zip"

          # Meta adatok a buildhez
          commit_sha="${GITHUB_SHA}"
          commit_msg="$(git log -1 --pretty=%B | tr -d '\r')"
          repo="${GITHUB_REPOSITORY}"
          run_url="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"

          # BUILDINFO.txt létrehozása
          {
            echo "REPO=${repo}"
            echo "COMMIT_SHA=${commit_sha}"
            echo "COMMIT_MSG=${commit_msg}"
            echo "UTC_TIME=${ts}"
            echo "RUN_URL=${run_url}"
          } > BUILDINFO.txt

          # ZIP (functions.php, style.css, .gitignore, BUILDINFO.txt)
          zip -j "dist/${zipname}" functions.php style.css .gitignore BUILDINFO.txt

          echo "ZIP_NAME=${zipname}" >> $GITHUB_ENV
          echo "TAG_NAME=backup-${{ github.run_number }}" >> $GITHUB_ENV
          echo "RELEASE_NAME=Auto backup #${{ github.run_number }} (${ts})" >> $GITHUB_ENV
