name: Theme Backup (ZIP to Releases)

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  schedule:
    - cron: "0 * * * *"

permissions:
  contents: write

concurrency:
  group: backup-${{ github.ref }}
  cancel-in-progress: false

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare ZIP with BUILDINFO
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p dist
          TS_UTC="$(date -u +'%Y%m%d-%H%M%S')"
          TS_BUD="$(TZ=Europe/Budapest date +'%Y%m%d-%H%M%S')"
          ZIPNAME="partdo-child-${TS_BUD}.zip"

          COMMIT_SHA="${GITHUB_SHA}"
          COMMIT_MSG="$(git log -1 --pretty=%B | tr -d '\r')"
          REPO="${GITHUB_REPOSITORY}"
          RUN_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
          BRANCH="${GITHUB_REF_NAME}"

          {
            echo "REPO=${REPO}"
            echo "BRANCH=${BRANCH}"
            echo "COMMIT_SHA=${COMMIT_SHA}"
            echo "COMMIT_MSG=${COMMIT_MSG}"
            echo "UTC_TIME=${TS_UTC}"
            echo "BUD_TIME=${TS_BUD}"
            echo "RUN_URL=${RUN_URL}"
          } > BUILDINFO.txt

          zip -j "dist/${ZIPNAME}" functions.php style.css .gitignore BUILDINFO.txt

          echo "ZIP_NAME=${ZIPNAME}" >> "$GITHUB_ENV"
          echo "TAG_NAME=backup-${TS_BUD}-${GITHUB_RUN_ID}" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=Auto backup ${TS_BUD} (RUN ${GITHUB_RUN_ID})" >> "$GITHUB_ENV"

      - name: Create Release & Upload ZIP (with PAT)
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: ${{ env.RELEASE_NAME }}
          body: |
            Automated backup
            - Repo: ${{ github.repository }}
            - Branch: ${{ github.ref_name }}
            - Commit: ${{ github.sha }}
            - Run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          files: |
            dist/${{ env.ZIP_NAME }}
